services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DbConnection=${DATABASE_URL}
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - internal-network
    restart: unless-stopped

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - internal-network
    restart: unless-stopped

networks:
  internal-network:
    driver: bridge
    internal: false
