name: Build and deploy on ZeroShare cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-images:
    runs-on: self-hosted
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      INACTIVITY_RETENTION_DAYS: ${{ vars.INACTIVITY_RETENTION_DAYS }}
      INTERVAL_CLEANUP_MINUTES: ${{ vars.INTERVAL_CLEANUP_MINUTES }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure SSL certificates exist
        run: |
          if [ ! -f /etc/letsencrypt/live/zeroshare.app/fullchain.pem ]; then
            echo "SSL certificates not found. Run: sudo certbot certonly --standalone -d zeroshare.app -d www.zeroshare.app"
            exit 1
          fi

      - name: Build images
        run: docker compose -f docker-compose.prod.yml build --no-cache

      - name: Stop containers
        run: docker compose -f docker-compose.prod.yml down

      - name: Start containers
        run: docker compose -f docker-compose.prod.yml up -d
